---
- name: Check services version and update service if file version updated
  hosts: win
  vars:
    services_path: # absolute path to services on Win machine
    services_names:
      # list with names of each service
    path_to_json_file: # absolute path to version.json
  roles:
    - parse-version-json
    - compare-services-versions
  post_tasks:
    - name: Update needed services
      include_role:
        name: update-services
      loop:
      - "{{ services_names }}"
      when: file_exists == false 
