---
- name: Launch test-service on winsw
  hosts: win
  tasks: 
    
    - name: Check test-service
      win_service: 
        name: test-java-service
      register: service_info
    
    - name: Stop test-service
      win_service:
        name: test-java-service
        state: stopped
      when: service_info == true

    - name: Remove test-service
      win_service:
        name: test-java-service
        state: absent
      when: service_info == true

    - name: Install and start test-service
      win_shell: |
        cd C:\winsw
        .\winsw install
        .\winsw start
      args:
        executable: powershell.exe
        
