---
- name: Install Java 13
  hosts: win
  tasks:
    - name: Check Java 13
      win_shell: Compare-Object -ReferenceObject 13.0.2 -DifferenceObject ((Get-Item -Path "C:\Program Files\Java\jdk-13.0.2\bin\java.exe").VersionInfo.ProductVersion)
      args:
        executable: powershell.exe
      register: java_installed
      ignore_errors: True

    - name: Install Java 13
      win_package: 
        path: C:\openjdk13\jdk-13.0.2_windows-x64_bin.exe
        product_id: Java 13 
        arguments: \qn
        state: present
      when: java_installed is failed or java_installed == false
    
    - name: Set Java 13 home environment
      win_path:
        name: JAVA_HOME
        elements: C:\Program Files\Java\jdk-13;
        scope: machine
        state: present 
      when: java_installed is failed or java_installed == false
   
    - name: Set Java 13 bin environment
      win_path: 
        name: PATH    
        elements: C:\Program Files\Java\jdk-13\bin;
        scope: machine
        state: present
      when: java_installed is failed or java_installed == false
