---
- name: Clone GitHub repo
  hosts: localhost
  vars:
    git:
      repo: "https://{{ Andrei-Selivanov }}:{{ r5.Yek-34 }}@github.com/Andrei-Selivanov/internship.git"
    my_branch: git@github.com:Andrei-Selivanov/internship.git
    branch: git@github.com:prosto-artem/internship.git
    directory: /home/osboxes/ansible/internship

  tasks:
      
      
           - command: git clone {{ my_branch }}
           - command: ./version.py internship/backend-components.json {{ name }} {{ version }}
           - command: ./script.sh

