- 
  name: Clone GitHub repo
  hosts: localhost
  vars:
    branch: https://github.com/prosto-artem/internship
    version: 1.0-commit1 

  tasks:
         
         - command: sudo git init
         - command: sudo git clone {{ branch }}
         - command: sudo ./script.py internship/version.json '"{{ version }}"'
 #       - command: sudo git commit -m "Commit version" internship/version.json
         - command: sudo git push -f origin master internship/version.json
         - command: cd ..
         - command: sudo rm -rf {{ directory }}
