- name: Clone GitHub repo
  hosts: localhost
  vars:
    my_branch: https://github.com/Andrei-Selivanov/internship
    branch: https://github.com/prosto-artem/internship
    version: 1.0-commit3 
    directory: /home/osboxes/ansible/internship

  tasks:
      
      
           - command: sudo git init
           - command: sudo git clone {{ branch }}
           - command: sudo ./script.py internship/version.json '"{{ version }}"'
           - command: cd internship/
           - command: sudo git fetch origin
           - command: chdir={{ directory }} sudo git add version.json 
           - command: sudo git config --global user.email "andrey46selivanov@gmail.com"
           - command: sudo git config --global user.name "Andrei-Selivanov"
           - command: chdir={{ directory }} sudo git commit -am "update version"  
#           - command: chdir={{ directory }} sudo git merge origin/master
           - command: chdir={{ directory }} sudo git pull {{ my_branch }}
           - command: chdir={{ directory }} sudo git push {{ my_branch }}
           - command: cd ..
           - command: sudo rm -rf internship/
