---
- name: Install PostgreSQL 12 from local rpm
  hosts: localhost
  tasks:
    
     - name: Copy rpm file to tmp folder
       copy: 
         src: "{{ item }}" 
         dest: "/tmp/{{ item }}"
       with_items:
         - postgresql12-libs-12.4-1PGDG.rhel7.x86_64.rpm
         - postgresql12-contrib-12.4-1PGDG.rhel7.x86_64.rpm
         - postgresql12-12.4-1PGDG.rhel7.x86_64.rpm
         - postgresql12-server-12.4-1PGDG.rhel7.x86_64.rpm

     - name: Install packages
       yum:
         name: "/tmp/{{ item }}"
         state: present
       with_items:
         - postgresql12-libs-12.4-1PGDG.rhel7.x86_64.rpm
         - postgresql12-contrib-12.4-1PGDG.rhel7.x86_64.rpm
         - postgresql12-12.4-1PGDG.rhel7.x86_64.rpm
         - postgresql12-server-12.4-1PGDG.rhel7.x86_64.rpm
       become: yes

     - name: Set PosgreSQL enviroment variables
       template: 
         src: postrgres.sh.j2
         dest: /etc/profile.d/postgres.sh
         mode: 0644
       notify: restart postgresql

     - name: Configure global settings for custom dirs for databases
       lineinfile:
         dest: "{{ postgresql_config_path }}/postgresql.conf"
         regexp: "^#/{{ item.option }}.+$"
         line: "{{ itme.option }} = '{{ item.value }}'"
         state: present
         mode: 0644
       with_items: "{{ postgresql_global_config_options }}"
       notify: restart postgresql

     - name: Configure host based authentication
       template:
         src: pg_hba.conf.j2
         dest: "{{ postgres_config_path }}/pg_hba.conf"
       notify: restart postgresql

  
     - name: Check if PostgreSQL database is initialized
       stat:
         path: "{{ postgresql_data_dir }}/PG_VERSION"
       register: pgdata_dir_version
 
     - name: Ensure PostgreSQL db is initialized
       command: "{{ postgresql_bin_path }}/initdb -D {{ postgresql_data_dir }}"
       when: pgdata_dir_version is not exists
       become: true
       become_user: "{{ postgresql_user }}"

     - name: Restart PostgreSQl service after setup
       service:
         name: postgre
         state: restarted


     
