---
- name: Installation ELK on machine
  hosts: localhost
  tasks:
    - name: Copy rpm files to /tmp
      copy:
        src: "files/{{ item }}"
        dest: "/tmp/{{ item }}"
      with_items:
      - elasticsearch-7.9.3-x86_64.rpm
      - logstash-7.9.3.rpm
      - kibana-7.9.3-x86_64.rpm

    - name: Install rpms
      yum:
        name: "/tmp/{{ item }}"
        state: present
      with_items:
      - elasticsearch-7.9.3-x86_64.rpm
      - logstash-7.9.3.rpm
      - kibana-7.9.3-x86_64.rpm
      become: yes 
    
    - name: Configure Elasticsearch
      template:
        src: elasticserach.yml.j2
        dest: "{{ elasticsearch_config_file_path }}"
        mode: "0644"
      notify: elasticsearch restart

    - name: Restart Elasticsearch service after configuration
      service:
        name: elasticsearch
        state: restarted
        enabled: true
      
    - name: Configure Logstash
      template: 
        src: logstash.yml.j2
        dest: "{{ logstash_config_file_path }}"
        mode: "0644"
      notify: logstash restart
   
    - name: Restart Logstash after configuration
      service:
        name: logstash
        state: restarted
        enabled: true
      
    - name: Configure Kibana
      template:
        src: kibana.yml.j2
        dest: "{{ kibana_config_file_path }}"
        mode: "0644"
      notify: kibana restart

    - name: Restart Kibana after configuration
      service:
        name: kibana
        state: restarted
        enabled: true
