---
- name: Check and install .Net Core 3.1
  hosts: win
  tasks:
        - name: Check .Net Core 3.1
          win_shell: |
            Compare-Object -ReferenceObject ('3,100,19,56502 @Commit: 65f04fb6db7a5e198d05dbebd5c4ad21eb018f89') -DifferenceObject ((Get-Item -Path 'C:\Program Files\dotnet\dotnet.exe').VersionInfo.ProductVersion)
          args:
            executable: powershell.exe
          register: dotnet_installed
          ignore_errors: True

        - name: Download .Net Core 3.1 
          win_package: 
            path: C:\dotnet_core_3.1\dotnet-sdk-3.1.100-win-x64.exe
            creates_path: C:\Program Files\dotnet.exe
            arguments: \qn
            state: present
          when: dotnet_installed is failed or dotnet_installed == false

        - name: Set .Net Core environment
          win_path: 
            name: PATH    
            elements: C:\Program Files\dotnet
            scope: machine
            state: present
          when: dotnet_installed is failed or dotnet_installed == false
