---
- name: Check services version and update service if file version updated
  hosts: win
  vars:
    services_path: # absolute path to services on Win machine
    services_names:  # list of names of each service 
    path_to_json_file: # absolute path to version.json
    path_to_files: # path to configuration files and scripts on local machine
  roles:
    - parse-version-json
    - compare-services-versions
  post_tasks:
    - name: Deploy configuration files
      include_vars: "{{ services_ names }}"
      win_template:
        src: configs.j2
        dest: "{{ path_to_files }}"\"{{ services_names }}"\"{{ item.path }}"
      with_filetree: "{{ service_configs }}"
      when: file_exists == false and item.state == 'file'

    - name: Update needed services
      include_role:
        name: update-services
      when: file_exists == false 
