---
- name: Check services version and update service if file version updated
  hosts: win
  vars:
    services_path: # absolute path to services on Win machine
    list_of_pairs: #[[ service_name1 , name_of_configuration_file1 ], ... etc ]
    services_names: "{{ dict(list_of_pairs) }}"
      # list of dictionaries with names of each service and name of their configuration file
    path_to_json_file: # absolute path to version.json
  roles:
    - parse-version-json
    - compare-services-versions
  post_tasks:
    - name: Update needed services
      include_role:
        name: update-services
      when: file_exists == false 
