---
elasticsearch_config_file_path: /etc/elasticsearch/elasticsearch.yml
elasticsearch_conf_settings:
  path.data: /var/lib/elasticsearch
  path.logs: /var/log/elasticsearch
  

logstash_config_file_path: /etc/logstash/logstash.yml
logstash_conf_settings:
  path.data: /var/lib/logstash
  path.config: /etc/logstash/conf.d
  path.logs: /var/log/logstash
  xpack.monitoring.elasticsearch.password: logstashpassword
  
kibana_config_file_path: /etc/kibana/kibana.yml
kibana_conf_settings:
  path.data: /var/lib/kibana
  logging.dest: /var/log/kibana
  elasticsearch.username: kibana-server
  elasticsearch.password: kibanapassword
