---
- name: Compare services versions
  hosts: win
  tasks:
    
    - name: Check service version file
      win_shell: Test-Path "{{ services_path }}"\"{{ service_name }}"\"{{ service_version }}"
      args:
        executable: powershell.exe
      register: file_exists
      
      

    
