---
- name: Update needed services
  hosts: win
  tasks:
    - name: Check test-service
      win_service: 
        name: "{{ services_name.key }}"
      register: service_info
    
    - name: Stop test-service
      win_service:
        name: "{{ services_name.key }}"
        state: stopped
      when: service_info == true 

    - name: Remove test-service
      win_service:
        name: "{{ services_name.key }}"
        state: absent
      when: service_info == true 

    - name: Deploy configuration file
      win_shell: |
      & "{{ path_to_files }}"\add_value_string.py "{{ config_name }}" "{{ service_name }}" "{{ value_string }}"
      Copy-Item -Path "{{ path_to_files }}"\"{{ config_name }}" -Destination "{{ services_path }}"\"{{ services_name }}"\"{{ config_name }}" 
      args:
        executable: powershell.exe

    - name: Install test-service
      win_shell: |
        & "{{ services_path }}"\"{{ services_name.key }}"\winsw.exe install
      args:
        executable: powershell.exe

    - name: Start test-service
      win_shell: |
        & "{{ services_path }}"\"{{ services_name.key }}"\winsw.exe start
      args:
        executable: powershell.exe

    - name: Create version file 
      win_shell: |
      cd "{{ services_path }}"\"{{ services_name.key }}"
      echo > $((Get-Item "{{ services_path }}"\"{{ services_name.key }}"\"{{ services_name.key }}".exe).VersionInfo.FileVersion)
      args:
        executable: powershell.exe
